### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [hacktivist123/Currency-Converter#1]
Hi @hacktivist123 .. I am a graphic designer, i wanna contribute for your project by proposing logo design and I've designed a logo for your project. What do you think? if you have an idea please share with me.
![cc](https://user-images.githubusercontent.com/36124339/45942656-8e576480-c00d-11e8-8d4c-e932541d7bf4.png)
Best Regard.

**Comment by hacktivist123** [comment]
Wow, I love them all but I prefer the first one

**Comment by mirzazulfan** [comment]
Thanks for your response @hacktivist123, I'm glad you liked it. Like this?
![cc 2](https://user-images.githubusercontent.com/36124339/45943164-71bc2c00-c00f-11e8-8dc4-8ad8a8ace4ed.png)

**Comment by hacktivist123** [comment]
Yes, send in a PR with the assets. Thanks!

**Comment by mirzazulfan** [comment]
You're welcome. I'll prepare the files, as soon as possible. and send you a pr. :+1:

**Comment by hacktivist123** [comment]
Great

On Sep 24, 2018 9:40 AM, "Mirza Zulfan" <notifications@github.com> wrote:

You're welcome. I'll prepare the files, as soon as possible. and send you a
pr. 👍

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hacktivist123/Currency-Converter/issues/1#issuecomment-423908509>,
or mute the thread

**Comment by mirzazulfan** [comment]
Hi @hacktivist123 i've created a pr. If you need anything change in the future, dont hesitate to contact me. Email : mirzazulfan@gmail.com

**Comment by hacktivist123** [comment]
Thanks
